{
 "title": "Common Graphql - overview",
 "description": "GraphQL Dashboard",
 "time": { "from": "2023-10-27T08:00:00.000Z", "to": "2023-10-27T09:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "GQL_NS", "query": "graphql-prod" },
   { "name": "GQL_NAME", "query": "common-graphql-telia" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fetch count",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(graphql_fetch_count{namespace=\"${GQL_NS}\",job=\"${GQL_NAME}\"}[5m])) by (url)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch timeout percentage",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "(sum(rate(graphql_fetch_timeout_count{namespace=\"${GQL_NS}\",job=\"${GQL_NAME}\"}[5m])) by (url) / sum(rate(graphql_fetch_count{namespace=\"${GQL_NS}\",job=\"${GQL_NAME}\"}[5m])) by (url)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GraphQL stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Incomming RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{namespace=\"istio-ingress\",destination_workload_namespace=\"${GQL_NS}\",destination_workload=\"${GQL_NAME}\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(graphqltest_process_cpu_seconds_total{namespace=\"${GQL_NS}\", pod=~\"${GQL_NAME}.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution time P99/P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "    histogram_quantile(0.99, \n        sum(irate(graphql_query_execution_time_seconds_bucket{namespace=\"${GQL_NS}\", job=\"${GQL_NAME}\"}[1m])) \n        by (le)\n    )",
     "legendFormat": "P99"
    },
    {
     "expr": "    histogram_quantile(0.95, \n        sum(irate(graphql_query_execution_time_seconds_bucket{namespace=\"${GQL_NS}\", job=\"${GQL_NAME}\"}[1m])) \n        by (le)\n    )",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Execution time P99/P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "    histogram_quantile(0.99, \n        sum(irate(graphql_query_execution_time_seconds_bucket{namespace=\"${GQL_NS}\", job=\"${GQL_NAME}\"}[1m])) \n        by (le)\n    )",
     "legendFormat": "P99"
    },
    {
     "expr": "    histogram_quantile(0.95, \n        sum(irate(graphql_query_execution_time_seconds_bucket{namespace=\"${GQL_NS}\", job=\"${GQL_NAME}\"}[1m])) \n        by (le)\n    )",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Running PODs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{namespace=\"${GQL_NS}\", pod=~\"${GQL_NAME}.*\"}) by(pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch invalid response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "sum(rate(graphql_fetch_invalid_response_count{namespace=\"${GQL_NS}\",job=\"${GQL_NAME}\"}[5m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Backend execution time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "unified series - upcoming episodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(graphql_fetch_time_seconds_bucket{namespace=\"${GQL_NS}\", job=\"${GQL_NAME}\"}[1m])) by (le, url) )",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}